const VehiclesActionTypes = {
  FETCH_VEHICLES_START: 'FETCH_VEHICLES_START',
  FETCH_VEHICLES_SUCCESS: 'FETCH_VEHICLES_SUCCESS',
  FETCH_VEHICLES_FAILURE: 'FETCH_VEHICLES_FAILURE',
  FETCH_VEHICLE_START: 'FETCH_VEHICLE_START',
  FETCH_VEHICLE_SUCCESS: 'FETCH_VEHICLE_SUCCESS',
  FETCH_VEHICLE_FAILURE: 'FETCH_VEHICLE_FAILURE',
};

export default VehiclesActionTypes;